name: validate Python
on:
 workflow_dispatch:
 pull_request:
  paths:
   - "**.py"
env:
 FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
 validate:
  runs-on: ubuntu-latest
  steps:
   - name: checkout repo
     uses: actions/checkout@v5
   - name: setup Python
     uses: actions/setup-python@v5
     with:
      python-version: '3.14'
   - name: syntax check
     run: |
      find . -type f -name "*.py" \
       ! -path "./.venv/*" \
       ! -path "./venv/*" \
       ! -path "./env/*" \
       ! -path "./__pycache__/*" \
       ! -path "./build/*" \
       ! -path "./dist/*" \
       -exec python -m py_compile {} +
   - name: install Flake8
     run: pip install flake8
   - name: lint
     run: |
      flake8 . \
       --indent-size=1 \
       --ignore=E225,E226,E231,E275,E301,E302,E303,E304,E305,E306,W292 \
       --exclude=.venv,venv,env,__pycache__,build,dist