name: validate scripts
on:
 workflow_dispatch:
env:
 FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
 validate-json:
  runs-on: ubuntu-latest
  steps:
   - name: checkout repo
     uses: actions/checkout@v5
   - name: setup py
     uses: actions/setup-python@v5
     with:
      python-version: '3.x'
   - name: validate py
     run: |
      python -m compileall